*This packet will be used to practice some basic NumPy functions using scenarios.*

# **Welcome explorer!** 

Congrats, you've done it, you've reached the center of the ruins. But alas, the secrets you've been searching for are encrypted with a puzzle. You have sufficient data and instructions on how to decrypt the final puzzle question, including:

*puzzle.question => Encrypted question you must decrypt and answer*

*puzzle.decrypted_half => part of the question's decryption key (instructions will come later pertaining to this)*

*puzzle.encrypted_half => part of the encrypted text we must decrypt (instructions will come later pertaining to this)*


*All located within the numpyEx class*



*We trust you will be successful in your mission, good luck!*

In [3]:
import numpy as np

# **numpyEx Class** *Do not expand, or exercise becomes boring*

*Please run all cells*

### numpyEx class definition

In [2]:
#@title
class numpyEx() :
  def __init__(self) :
      self.question = np.array(['the', 'pineapple', 'in', 'under', 'who', 'a', 'sea', 'lives'])
      self.decrypted_half = np.array([[53, 322], [680, 73]])
      self.encrypted_half = np.array([568, 224, 206, 278, 388])
      self.status = False

  def check_encryption(self, ind) :
    correct = np.array([4, 7, 2, 5, 1, 3, 0, 6])
    if(np.array_equal(ind, correct)) : 
      self.status = True
      print('Correct, Please apply this to the question.')
    else :
      print('Incorrect key')

  def check_answer(self, answer) :
    if(self.status == False) : print("Must decrypt question first!")
    else:
      if(answer.lower()== 'spongebob' or answer.lower()== 'spongebob squarepants') : print("Correct!")
      else : print("Incorrect, please try again.")

# **The Challenge**

First thing first, let's see what we are working with. I've created the puzzle for you already, explorer. Feel free to observe the question.

In [6]:
puzzle = numpyEx()
puzzle.question

array(['the', 'pineapple', 'in', 'under', 'who', 'a', 'sea', 'lives'],
      dtype='<U9')

As you've just confirmed, the puzzle is scrambled. Now we could brute force the solution, but that's not the explorer way. For the first step of the decryption process, please create an array of five 1s (ex: [1, 1, 1, 1, 1]).

In [7]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


Great! Now we are going to have to get an array containing the sum of our created array and the stored encryption within the puzzle.

In [9]:
sum_array = np.add(ones_array, puzzle.encrypted_half)
print(sum_array)

[569. 225. 207. 279. 389.]


Strange. You're array is looking a little long... We almost forgot! Remove the smallest element in the array.

In [10]:
min_index = np.argmin(sum_array)
new_array = np.delete(sum_array, min_index)
print(new_array)

[569. 225. 279. 389.]


Now it looks fabulous! Let's get back on track with these steps. Next find the rounded (ceiling) mean of your array and save it.

In [11]:
mean = np.mean(new_array)
rounded_mean = np.ceil(mean).astype(int)
print(rounded_mean)

366


For the next part, you will have to replace the second element in the array with the calculated mean (remember, it is an array of ints)

We're almost there explore, just keep holding out!

Someone else has already solved the second half of the puzzle, but if we observe the shape of the stored array, there's a problem. Our calculated array and the other half have mismatching shapes!

We need to adjust the shape of our array to match the key_half already stored within the puzzle

Now that two array shapes match, we can combine the two arrays.

Remember, our array is the first half of the puzzle and the stored array is the second half

To get our final decryption key, we must transform our array to be 1-Dimensional and get the sorted indices

Before you proceed to apply the encryption to the puzzle question, please check it with this function. *Puzzle will not be completed without correct decryption key*

In [ ]:
puzzle.check_encryption()

It's go time! Decrypt the puzzle question by applying the calculated sort order to the question array.

This is the final step explorer, check your answer against this function. You'll see if it's correct.

In [ ]:
puzzle.check_answer()

# **Finishing remarks**

Thank you explorer! We found the secrets and live to tell the tale. Who knew the answer would be so deep and profound. Generations will tell your story. Be proud explorer, we couldn't have done it without you!

